-- MySQL Script generated by MySQL Workbench
-- Sun Jun 11 18:48:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`razonesSociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`razonesSociales` (
  `idRazonSocial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(1) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRazonSocial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `domicilio` VARCHAR(256) NOT NULL,
  `idRazonSocial` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_rsocial_idx` (`idRazonSocial` ASC),
  CONSTRAINT `fk_cliente_rsocial`
    FOREIGN KEY (`idRazonSocial`)
    REFERENCES `mydb`.`razonesSociales` (`idRazonSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyectos` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT(512) NOT NULL,
  `cauntia` FLOAT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idProyecto`),
  INDEX `fk_proyecto_cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_proyecto_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bancos` (
  `idBanco` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idBanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`colaboradores` (
  `idColaborador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(256) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `idBanco` INT NOT NULL,
  `cuenta` VARCHAR(25) NOT NULL,
  `idRazonSocial` DATETIME NOT NULL,
  PRIMARY KEY (`idColaborador`),
  INDEX `fk_colaborador_rsocial1_idx` (`idRazonSocial` ASC),
  INDEX `fk_colaborador_banco1_idx` (`idBanco` ASC),
  CONSTRAINT `fk_colaborador_rsocial1`
    FOREIGN KEY (`idRazonSocial`)
    REFERENCES `mydb`.`razonesSociales` (`idRazonSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaborador_banco1`
    FOREIGN KEY (`idBanco`)
    REFERENCES `mydb`.`bancos` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colaboradoresProyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`colaboradoresProyectos` (
  `idProyecto` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  INDEX `fk_proyecto_has_colaborador_colaborador1_idx` (`idColaborador` ASC),
  INDEX `fk_proyecto_has_colaborador_proyecto1_idx` (`idProyecto` ASC),
  PRIMARY KEY (`idProyecto`, `idColaborador`),
  CONSTRAINT `fk_proyecto_has_colaborador_proyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `mydb`.`proyectos` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_has_colaborador_colaborador1`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `mydb`.`colaboradores` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tiposPagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tiposPagos` (
  `idTiposPagos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTiposPagos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagos` (
  `idPago` INT NOT NULL,
  `concepto` VARCHAR(256) NOT NULL,
  `monto` FLOAT NOT NULL,
  `fechaPago` DATE NOT NULL,
  `idProyecto` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  `idTipoPago` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_pago_proyecto_has_colaborador1_idx` (`idProyecto` ASC, `idColaborador` ASC),
  INDEX `fk_pago_tipo_pago1_idx` (`idTipoPago` ASC),
  CONSTRAINT `fk_pago_proyecto_has_colaborador1`
    FOREIGN KEY (`idProyecto` , `idColaborador`)
    REFERENCES `mydb`.`colaboradoresProyectos` (`idProyecto` , `idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_tipo_pago1`
    FOREIGN KEY (`idTipoPago`)
    REFERENCES `mydb`.`tiposPagos` (`idTiposPagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
